// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfileApi.Infrastructure;

namespace ProfileApi.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20201008175726_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ProfileApi.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 697,
                            Address = "1379 Zulauf Well",
                            Birthdate = new DateTime(1973, 7, 1, 4, 23, 31, 36, DateTimeKind.Utc).AddTicks(2400),
                            City = "Walkerborough",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 36, DateTimeKind.Utc).AddTicks(7040),
                            Email = "hilton_reichel@troy.net",
                            Favorite = false,
                            Name = "Ashly O'Hara",
                            Phonenumber = "1-8106-122-6925",
                            Photo = "https://randomuser.me/api/portraits/men/40.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 36, DateTimeKind.Utc).AddTicks(7500)
                        },
                        new
                        {
                            Id = 695,
                            Address = "89579 Koepp Roads",
                            Birthdate = new DateTime(1981, 2, 11, 8, 35, 53, 31, DateTimeKind.Utc).AddTicks(2230),
                            City = "D'Amoreland",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 31, DateTimeKind.Utc).AddTicks(6400),
                            Email = "jade@raphael.info",
                            Favorite = false,
                            Name = "Bell Schaefer",
                            Phonenumber = "1-1009-265-3975 x0010",
                            Photo = "https://randomuser.me/api/portraits/men/38.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 31, DateTimeKind.Utc).AddTicks(6700)
                        },
                        new
                        {
                            Id = 705,
                            Address = "2910 Mortimer Hollow",
                            Birthdate = new DateTime(1978, 7, 12, 21, 44, 44, 50, DateTimeKind.Utc).AddTicks(3180),
                            City = "Lake Tara",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 50, DateTimeKind.Utc).AddTicks(7720),
                            Email = "karina@margret.net",
                            Favorite = false,
                            Name = "Benedict VonRueden",
                            Phonenumber = "157-986-37107 x687",
                            Photo = "https://randomuser.me/api/portraits/women/48.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 50, DateTimeKind.Utc).AddTicks(8070)
                        },
                        new
                        {
                            Id = 680,
                            Address = "2814 Howe Ways",
                            Birthdate = new DateTime(2000, 7, 3, 1, 57, 13, 3, DateTimeKind.Utc).AddTicks(6340),
                            City = "East Katlynnhaven",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 4, DateTimeKind.Utc).AddTicks(1240),
                            Email = "reina_stehr@elsa.name",
                            Favorite = false,
                            Name = "Christine Jacobs",
                            Phonenumber = "646.634.3900",
                            Photo = "https://randomuser.me/api/portraits/women/23.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 4, DateTimeKind.Utc).AddTicks(1640)
                        },
                        new
                        {
                            Id = 691,
                            Address = "129 Maverick Bridge",
                            Birthdate = new DateTime(1974, 9, 25, 22, 5, 54, 23, DateTimeKind.Utc).AddTicks(7360),
                            City = "North Junius",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 24, DateTimeKind.Utc).AddTicks(2270),
                            Email = "mckenzie@blaise.me",
                            Favorite = false,
                            Name = "Clyde Nikolaus II",
                            Phonenumber = "(51010)967-7197",
                            Photo = "https://randomuser.me/api/portraits/women/34.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 24, DateTimeKind.Utc).AddTicks(2710)
                        },
                        new
                        {
                            Id = 664,
                            Address = "82186 Macejkovic Corner",
                            Birthdate = new DateTime(1979, 7, 13, 10, 24, 37, 971, DateTimeKind.Utc).AddTicks(9400),
                            City = "North Donatoberg",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 972, DateTimeKind.Utc).AddTicks(4170),
                            Email = "jerry.cole@ben.net",
                            Favorite = false,
                            Name = "Dangelo Boehm",
                            Phonenumber = "1-413-997-09310",
                            Photo = "https://randomuser.me/api/portraits/women/7.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 972, DateTimeKind.Utc).AddTicks(4550)
                        },
                        new
                        {
                            Id = 698,
                            Address = "6319 Mariana Vista",
                            Birthdate = new DateTime(1985, 2, 1, 6, 30, 41, 37, DateTimeKind.Utc).AddTicks(9850),
                            City = "Lake Breana",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 38, DateTimeKind.Utc).AddTicks(4620),
                            Email = "deanna_schmitt@zoey.tv",
                            Favorite = false,
                            Name = "Delfina Anderson",
                            Phonenumber = "(239)926-26103",
                            Photo = "https://randomuser.me/api/portraits/men/41.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 38, DateTimeKind.Utc).AddTicks(4990)
                        },
                        new
                        {
                            Id = 702,
                            Address = "943 Johnny Summit",
                            Birthdate = new DateTime(1989, 6, 9, 6, 37, 49, 44, DateTimeKind.Utc).AddTicks(5680),
                            City = "Runolfsdottirside",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 45, DateTimeKind.Utc).AddTicks(230),
                            Email = "annabelle@sofia.ca",
                            Favorite = false,
                            Name = "Dock Gislason",
                            Phonenumber = "1-408-128-1614 x238",
                            Photo = "https://randomuser.me/api/portraits/women/45.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 45, DateTimeKind.Utc).AddTicks(580)
                        },
                        new
                        {
                            Id = 658,
                            Address = "258 Hank Brooks",
                            Birthdate = new DateTime(1985, 11, 1, 6, 59, 6, 960, DateTimeKind.Utc).AddTicks(920),
                            City = "West Lilliana",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 960, DateTimeKind.Utc).AddTicks(5990),
                            Email = "jaron.shields@angie.biz",
                            Favorite = false,
                            Name = "Domingo White",
                            Phonenumber = "(498)2105-4380",
                            Photo = "https://randomuser.me/api/portraits/men/1.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 960, DateTimeKind.Utc).AddTicks(6370)
                        },
                        new
                        {
                            Id = 700,
                            Address = "38105 Weimann Cliffs",
                            Birthdate = new DateTime(1992, 8, 5, 22, 48, 15, 41, DateTimeKind.Utc).AddTicks(2680),
                            City = "New Josiannetown",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 41, DateTimeKind.Utc).AddTicks(7200),
                            Email = "lavinia_walsh@emanuel.us",
                            Favorite = false,
                            Name = "Drake Murray",
                            Phonenumber = "(936)532-4061",
                            Photo = "https://randomuser.me/api/portraits/women/43.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 41, DateTimeKind.Utc).AddTicks(7570)
                        },
                        new
                        {
                            Id = 679,
                            Address = "721 Daugherty Corner",
                            Birthdate = new DateTime(1990, 10, 2, 22, 36, 1, 1, DateTimeKind.Utc).AddTicks(8720),
                            City = "Russelmouth",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 2, DateTimeKind.Utc).AddTicks(3550),
                            Email = "kennedy@lorna.org",
                            Favorite = false,
                            Name = "Emilio Christiansen",
                            Phonenumber = "1-671-879-101003",
                            Photo = "https://randomuser.me/api/portraits/women/22.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 2, DateTimeKind.Utc).AddTicks(3980)
                        },
                        new
                        {
                            Id = 685,
                            Address = "19729 Jamarcus Views",
                            Birthdate = new DateTime(1995, 7, 18, 15, 19, 44, 12, DateTimeKind.Utc).AddTicks(5030),
                            City = "Aufderharberg",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 12, DateTimeKind.Utc).AddTicks(9780),
                            Email = "nels.johns@verlie.com",
                            Favorite = false,
                            Name = "Emmie Sporer",
                            Phonenumber = "(1001)159-76210",
                            Photo = "https://randomuser.me/api/portraits/men/28.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 13, DateTimeKind.Utc).AddTicks(170)
                        },
                        new
                        {
                            Id = 706,
                            Address = "596 Hansen Motorway",
                            Birthdate = new DateTime(1977, 7, 15, 5, 3, 12, 52, DateTimeKind.Utc).AddTicks(6870),
                            City = "McCluremouth",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 53, DateTimeKind.Utc).AddTicks(1440),
                            Email = "merle@emilio.biz",
                            Favorite = false,
                            Name = "Enos Osinski",
                            Phonenumber = "1-251-1022-104110 x47110",
                            Photo = "https://randomuser.me/api/portraits/men/49.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 53, DateTimeKind.Utc).AddTicks(1820)
                        },
                        new
                        {
                            Id = 674,
                            Address = "352 Christiansen Plain",
                            Birthdate = new DateTime(1987, 6, 23, 19, 46, 12, 992, DateTimeKind.Utc).AddTicks(6920),
                            City = "Heidenreichshire",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 993, DateTimeKind.Utc).AddTicks(900),
                            Email = "carmine@milton.biz",
                            Favorite = false,
                            Name = "Era Satterfield PhD",
                            Phonenumber = "1-10510-1104-3789",
                            Photo = "https://randomuser.me/api/portraits/men/17.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 993, DateTimeKind.Utc).AddTicks(1230)
                        },
                        new
                        {
                            Id = 663,
                            Address = "825 Sylvester Junction",
                            Birthdate = new DateTime(1977, 12, 10, 9, 33, 0, 970, DateTimeKind.Utc).AddTicks(1030),
                            City = "New Aricside",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 970, DateTimeKind.Utc).AddTicks(6350),
                            Email = "brandt@jalon.me",
                            Favorite = false,
                            Name = "Everett Erdman",
                            Phonenumber = "439.618.8041",
                            Photo = "https://randomuser.me/api/portraits/men/6.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 970, DateTimeKind.Utc).AddTicks(6750)
                        },
                        new
                        {
                            Id = 683,
                            Address = "494 Ward Light",
                            Birthdate = new DateTime(1992, 7, 19, 0, 16, 7, 9, DateTimeKind.Utc).AddTicks(350),
                            City = "Einoshire",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 9, DateTimeKind.Utc).AddTicks(5280),
                            Email = "marcia_kessler@suzanne.net",
                            Favorite = false,
                            Name = "Ewell Hegmann",
                            Phonenumber = "1-361-455-2962",
                            Photo = "https://randomuser.me/api/portraits/men/26.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 9, DateTimeKind.Utc).AddTicks(5660)
                        },
                        new
                        {
                            Id = 701,
                            Address = "071034 Humberto Pike",
                            Birthdate = new DateTime(1971, 5, 17, 9, 21, 15, 42, DateTimeKind.Utc).AddTicks(9030),
                            City = "Curtbury",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 43, DateTimeKind.Utc).AddTicks(3510),
                            Email = "josephine@carlos.tv",
                            Favorite = false,
                            Name = "Finn Shanahan",
                            Phonenumber = "1-354-3104-21029 x59324",
                            Photo = "https://randomuser.me/api/portraits/men/44.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 43, DateTimeKind.Utc).AddTicks(3810)
                        },
                        new
                        {
                            Id = 660,
                            Address = "8102104 Kian Union",
                            Birthdate = new DateTime(1981, 6, 14, 0, 34, 30, 963, DateTimeKind.Utc).AddTicks(8150),
                            City = "East Mattie",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 964, DateTimeKind.Utc).AddTicks(3520),
                            Email = "tyree.mayer@malika.ca",
                            Favorite = false,
                            Name = "German Blanda II",
                            Phonenumber = "1081-863-5347 x02106",
                            Photo = "https://randomuser.me/api/portraits/men/3.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 964, DateTimeKind.Utc).AddTicks(3880)
                        },
                        new
                        {
                            Id = 687,
                            Address = "506 Parker Stream",
                            Birthdate = new DateTime(1977, 4, 19, 23, 56, 9, 15, DateTimeKind.Utc).AddTicks(8780),
                            City = "Kihnhaven",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 16, DateTimeKind.Utc).AddTicks(3370),
                            Email = "vaughn@eleonore.biz",
                            Favorite = false,
                            Name = "Hazle Beer",
                            Phonenumber = "934-491-8855",
                            Photo = "https://randomuser.me/api/portraits/men/30.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 16, DateTimeKind.Utc).AddTicks(3740)
                        },
                        new
                        {
                            Id = 659,
                            Address = "056 VonRueden Throughway",
                            Birthdate = new DateTime(1998, 8, 27, 18, 35, 12, 962, DateTimeKind.Utc).AddTicks(140),
                            City = "Kutchtown",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 962, DateTimeKind.Utc).AddTicks(4560),
                            Email = "oleta.hessel@mayra.biz",
                            Favorite = false,
                            Name = "Jazmin Bode",
                            Phonenumber = "1-330-349-8362",
                            Photo = "https://randomuser.me/api/portraits/men/2.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 962, DateTimeKind.Utc).AddTicks(4890)
                        },
                        new
                        {
                            Id = 675,
                            Address = "4497 Vickie Spurs",
                            Birthdate = new DateTime(1979, 11, 1, 8, 4, 36, 994, DateTimeKind.Utc).AddTicks(3530),
                            City = "Lake Jaidenton",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 994, DateTimeKind.Utc).AddTicks(7900),
                            Email = "beulah@neha.ca",
                            Favorite = false,
                            Name = "Joan Daniel",
                            Phonenumber = "049-1080-2551",
                            Photo = "https://randomuser.me/api/portraits/men/18.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 994, DateTimeKind.Utc).AddTicks(8210)
                        },
                        new
                        {
                            Id = 670,
                            Address = "490 Willms Cliffs",
                            Birthdate = new DateTime(1988, 6, 28, 18, 39, 21, 982, DateTimeKind.Utc).AddTicks(7910),
                            City = "Minervaside",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 983, DateTimeKind.Utc).AddTicks(6490),
                            Email = "missouri@arthur.org",
                            Favorite = false,
                            Name = "Kamron Jacobi I",
                            Phonenumber = "412.343.2782 x759",
                            Photo = "https://randomuser.me/api/portraits/men/13.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 983, DateTimeKind.Utc).AddTicks(7130)
                        },
                        new
                        {
                            Id = 665,
                            Address = "046910 Grant Lane",
                            Birthdate = new DateTime(1974, 10, 12, 12, 26, 23, 973, DateTimeKind.Utc).AddTicks(6180),
                            City = "North Johnmouth",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 974, DateTimeKind.Utc).AddTicks(990),
                            Email = "deshawn_nolan@rey.biz",
                            Favorite = false,
                            Name = "Kenna Bradtke",
                            Phonenumber = "1-399-797-3337 x39402",
                            Photo = "https://randomuser.me/api/portraits/men/8.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 974, DateTimeKind.Utc).AddTicks(1370)
                        },
                        new
                        {
                            Id = 694,
                            Address = "760 Sammy Dale",
                            Birthdate = new DateTime(1974, 2, 26, 16, 3, 0, 29, DateTimeKind.Utc).AddTicks(6950),
                            City = "Guªannbury",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 30, DateTimeKind.Utc).AddTicks(1090),
                            Email = "florencio.fisher@wendell.tv",
                            Favorite = false,
                            Name = "Laverne Gleichner",
                            Phonenumber = "(081)291-9173 x3567",
                            Photo = "https://randomuser.me/api/portraits/women/37.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 30, DateTimeKind.Utc).AddTicks(1440)
                        },
                        new
                        {
                            Id = 669,
                            Address = "925 Dena Manors",
                            Birthdate = new DateTime(1971, 5, 24, 10, 52, 43, 980, DateTimeKind.Utc).AddTicks(6400),
                            City = "South Jimmieburgh",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 981, DateTimeKind.Utc).AddTicks(1830),
                            Email = "kirstin.gleichner@samir.org",
                            Favorite = false,
                            Name = "Leda Dach",
                            Phonenumber = "186.558.8870",
                            Photo = "https://randomuser.me/api/portraits/women/12.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 981, DateTimeKind.Utc).AddTicks(2230)
                        },
                        new
                        {
                            Id = 657,
                            Address = "603 Gusikowski Lodge",
                            Birthdate = new DateTime(1990, 2, 21, 21, 44, 53, 956, DateTimeKind.Utc).AddTicks(3670),
                            City = "East Liammouth",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 956, DateTimeKind.Utc).AddTicks(9490),
                            Email = "bernie@elwin.tv",
                            Favorite = false,
                            Name = "Lenora Waters",
                            Phonenumber = "516-492-10574 x410624",
                            Photo = "https://randomuser.me/api/portraits/men/0.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 956, DateTimeKind.Utc).AddTicks(9970)
                        },
                        new
                        {
                            Id = 678,
                            Address = "049 Javon Squares",
                            Birthdate = new DateTime(2001, 11, 26, 15, 47, 26, 999, DateTimeKind.Utc).AddTicks(9980),
                            City = "New Coleman",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 0, DateTimeKind.Utc).AddTicks(5290),
                            Email = "ewell@joseph.me",
                            Favorite = false,
                            Name = "Levi Keebler",
                            Phonenumber = "300-597-1976",
                            Photo = "https://randomuser.me/api/portraits/men/21.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 0, DateTimeKind.Utc).AddTicks(5660)
                        },
                        new
                        {
                            Id = 690,
                            Address = "21010 Barton Mountains",
                            Birthdate = new DateTime(1972, 8, 11, 14, 58, 56, 21, DateTimeKind.Utc).AddTicks(9820),
                            City = "Russelfurt",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 22, DateTimeKind.Utc).AddTicks(4920),
                            Email = "isaac_gottlieb@erica.biz",
                            Favorite = false,
                            Name = "Liza Hintz",
                            Phonenumber = "(991)568-8515",
                            Photo = "https://randomuser.me/api/portraits/men/33.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 22, DateTimeKind.Utc).AddTicks(5350)
                        },
                        new
                        {
                            Id = 684,
                            Address = "1007 Hirthe Camp",
                            Birthdate = new DateTime(1999, 5, 23, 4, 34, 4, 10, DateTimeKind.Utc).AddTicks(8250),
                            City = "Lake Carmela",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 11, DateTimeKind.Utc).AddTicks(2770),
                            Email = "lina@dan.us",
                            Favorite = false,
                            Name = "Maribel Blanda",
                            Phonenumber = "319.416.70810",
                            Photo = "https://randomuser.me/api/portraits/women/27.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 11, DateTimeKind.Utc).AddTicks(3120)
                        },
                        new
                        {
                            Id = 686,
                            Address = "2734 Victor Mall",
                            Birthdate = new DateTime(1985, 7, 9, 14, 33, 3, 14, DateTimeKind.Utc).AddTicks(2190),
                            City = "Gottliebmouth",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 14, DateTimeKind.Utc).AddTicks(6830),
                            Email = "camryn_stroman@jermain.us",
                            Favorite = false,
                            Name = "Mekhi Heaney",
                            Phonenumber = "1-2104-1108-5410 x410106",
                            Photo = "https://randomuser.me/api/portraits/women/29.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 14, DateTimeKind.Utc).AddTicks(7190)
                        },
                        new
                        {
                            Id = 689,
                            Address = "1069 Abelardo Viaduct",
                            Birthdate = new DateTime(1994, 10, 17, 8, 55, 23, 19, DateTimeKind.Utc).AddTicks(6640),
                            City = "Leannonhaven",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 20, DateTimeKind.Utc).AddTicks(1640),
                            Email = "danyka_o.hara@naomi.tv",
                            Favorite = false,
                            Name = "Michele Morissette",
                            Phonenumber = "188.970.2616 x8877",
                            Photo = "https://randomuser.me/api/portraits/women/32.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 20, DateTimeKind.Utc).AddTicks(1970)
                        },
                        new
                        {
                            Id = 661,
                            Address = "280210 Veronica Loaf",
                            Birthdate = new DateTime(1978, 11, 9, 20, 44, 32, 965, DateTimeKind.Utc).AddTicks(7520),
                            City = "McDermottville",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 966, DateTimeKind.Utc).AddTicks(3260),
                            Email = "gabrielle@madelyn.biz",
                            Favorite = false,
                            Name = "Miss America Mills",
                            Phonenumber = "662-150-6104",
                            Photo = "https://randomuser.me/api/portraits/men/4.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 966, DateTimeKind.Utc).AddTicks(3730)
                        },
                        new
                        {
                            Id = 704,
                            Address = "831 Douglas Corner",
                            Birthdate = new DateTime(1984, 2, 6, 3, 1, 17, 48, DateTimeKind.Utc).AddTicks(7140),
                            City = "Dovieville",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 49, DateTimeKind.Utc).AddTicks(1370),
                            Email = "jannie@marisol.org",
                            Favorite = false,
                            Name = "Miss Jayce Aufderhar",
                            Phonenumber = "114.003.8146",
                            Photo = "https://randomuser.me/api/portraits/women/47.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 49, DateTimeKind.Utc).AddTicks(1700)
                        },
                        new
                        {
                            Id = 696,
                            Address = "191 Bins Avenue",
                            Birthdate = new DateTime(1978, 3, 1, 7, 18, 6, 33, DateTimeKind.Utc).AddTicks(3830),
                            City = "Lindbury",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 34, DateTimeKind.Utc).AddTicks(2850),
                            Email = "shad.king@lauriane.us",
                            Favorite = false,
                            Name = "Mr. Dillan Kihn",
                            Phonenumber = "305.949.0595 x3580",
                            Photo = "https://randomuser.me/api/portraits/women/39.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 34, DateTimeKind.Utc).AddTicks(3760)
                        },
                        new
                        {
                            Id = 671,
                            Address = "567 Jerald Unions",
                            Birthdate = new DateTime(1968, 7, 24, 3, 54, 40, 986, DateTimeKind.Utc).AddTicks(3730),
                            City = "Oberbrunnerport",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 987, DateTimeKind.Utc).AddTicks(4260),
                            Email = "ethelyn.borer@rogelio.ca",
                            Favorite = false,
                            Name = "Mrs. Grady Walker",
                            Phonenumber = "(669)949-10338 x027",
                            Photo = "https://randomuser.me/api/portraits/women/14.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 987, DateTimeKind.Utc).AddTicks(4720)
                        },
                        new
                        {
                            Id = 688,
                            Address = "483107 Darby Unions",
                            Birthdate = new DateTime(1977, 7, 26, 19, 49, 11, 17, DateTimeKind.Utc).AddTicks(7040),
                            City = "Lake Rosario",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 18, DateTimeKind.Utc).AddTicks(3100),
                            Email = "clifford_kunde@milan.info",
                            Favorite = false,
                            Name = "Nannie Schinner",
                            Phonenumber = "(651)1108-2550 x870",
                            Photo = "https://randomuser.me/api/portraits/men/31.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 18, DateTimeKind.Utc).AddTicks(3520)
                        },
                        new
                        {
                            Id = 667,
                            Address = "455 Auer Lock",
                            Birthdate = new DateTime(1980, 11, 6, 9, 16, 40, 976, DateTimeKind.Utc).AddTicks(9850),
                            City = "Beermouth",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 977, DateTimeKind.Utc).AddTicks(4060),
                            Email = "tillman@allene.name",
                            Favorite = false,
                            Name = "Nestor Reichel",
                            Phonenumber = "1-442-1610-73108",
                            Photo = "https://randomuser.me/api/portraits/men/10.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 977, DateTimeKind.Utc).AddTicks(4430)
                        },
                        new
                        {
                            Id = 693,
                            Address = "473 Heaney Lights",
                            Birthdate = new DateTime(1994, 12, 16, 8, 48, 45, 28, DateTimeKind.Utc).AddTicks(1100),
                            City = "Douglasburgh",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 28, DateTimeKind.Utc).AddTicks(5480),
                            Email = "kadin@mina.biz",
                            Favorite = false,
                            Name = "Robb Jacobson",
                            Phonenumber = "1-873-185-66103 x27455",
                            Photo = "https://randomuser.me/api/portraits/women/36.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 28, DateTimeKind.Utc).AddTicks(5850)
                        },
                        new
                        {
                            Id = 681,
                            Address = "048 Jovan Squares",
                            Birthdate = new DateTime(2000, 5, 3, 18, 19, 22, 5, DateTimeKind.Utc).AddTicks(3780),
                            City = "New Amarafort",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 5, DateTimeKind.Utc).AddTicks(8600),
                            Email = "alia@sydni.com",
                            Favorite = false,
                            Name = "Roosevelt Daniel",
                            Phonenumber = "1-388-571-9046",
                            Photo = "https://randomuser.me/api/portraits/women/24.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 5, DateTimeKind.Utc).AddTicks(8970)
                        },
                        new
                        {
                            Id = 673,
                            Address = "51040 Parisian Causeway",
                            Birthdate = new DateTime(1981, 7, 28, 14, 9, 53, 991, DateTimeKind.Utc).AddTicks(80),
                            City = "South Eliane",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 991, DateTimeKind.Utc).AddTicks(4830),
                            Email = "triston@guiseppe.net",
                            Favorite = false,
                            Name = "Rose Hessel IV",
                            Phonenumber = "1-207-153-8194",
                            Photo = "https://randomuser.me/api/portraits/men/16.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 991, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 668,
                            Address = "88582 Gleichner Stravenue",
                            Birthdate = new DateTime(1967, 2, 19, 9, 57, 21, 978, DateTimeKind.Utc).AddTicks(7030),
                            City = "New Heberhaven",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 979, DateTimeKind.Utc).AddTicks(1820),
                            Email = "pinkie_heaney@elva.biz",
                            Favorite = false,
                            Name = "Shanny Robel",
                            Phonenumber = "981-643-21062 x2510",
                            Photo = "https://randomuser.me/api/portraits/women/11.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 979, DateTimeKind.Utc).AddTicks(2190)
                        },
                        new
                        {
                            Id = 672,
                            Address = "614 Xzavier Fork",
                            Birthdate = new DateTime(1996, 11, 3, 21, 20, 9, 988, DateTimeKind.Utc).AddTicks(9770),
                            City = "Port Annaliseburgh",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 989, DateTimeKind.Utc).AddTicks(5390),
                            Email = "jordan@malinda.us",
                            Favorite = false,
                            Name = "Sigurd Muller",
                            Phonenumber = "1-081-699-31088 x762",
                            Photo = "https://randomuser.me/api/portraits/men/15.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 989, DateTimeKind.Utc).AddTicks(5910)
                        },
                        new
                        {
                            Id = 699,
                            Address = "064 Murazik Forks",
                            Birthdate = new DateTime(1992, 11, 20, 18, 19, 42, 39, DateTimeKind.Utc).AddTicks(6180),
                            City = "Welchton",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 40, DateTimeKind.Utc).AddTicks(440),
                            Email = "khalil@yesenia.biz",
                            Favorite = false,
                            Name = "Sophia Ernser PhD",
                            Phonenumber = "137.854.4195",
                            Photo = "https://randomuser.me/api/portraits/men/42.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 40, DateTimeKind.Utc).AddTicks(800)
                        },
                        new
                        {
                            Id = 682,
                            Address = "418 Ruth Meadow",
                            Birthdate = new DateTime(1986, 7, 31, 11, 44, 48, 7, DateTimeKind.Utc).AddTicks(1220),
                            City = "Gorczanyhaven",
                            Country = "England",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 7, DateTimeKind.Utc).AddTicks(6090),
                            Email = "philip_greenfelder@ezekiel.co.uk",
                            Favorite = false,
                            Name = "Terence Koepp",
                            Phonenumber = "621-1103-18910 x6913",
                            Photo = "https://randomuser.me/api/portraits/men/25.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 7, DateTimeKind.Utc).AddTicks(6440)
                        },
                        new
                        {
                            Id = 677,
                            Address = "1073 Kareem Road",
                            Birthdate = new DateTime(1977, 8, 16, 15, 17, 11, 998, DateTimeKind.Utc).AddTicks(3500),
                            City = "South Anguston",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 998, DateTimeKind.Utc).AddTicks(8240),
                            Email = "calista.dach@gayle.co.uk",
                            Favorite = false,
                            Name = "Tony Harris",
                            Phonenumber = "1-913-670-7023",
                            Photo = "https://randomuser.me/api/portraits/men/20.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 998, DateTimeKind.Utc).AddTicks(8540)
                        },
                        new
                        {
                            Id = 703,
                            Address = "167 Abigayle Green",
                            Birthdate = new DateTime(1982, 8, 11, 21, 0, 9, 46, DateTimeKind.Utc).AddTicks(7830),
                            City = "East Cliffordmouth",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 47, DateTimeKind.Utc).AddTicks(2640),
                            Email = "julianne@brielle.org",
                            Favorite = false,
                            Name = "Unique Volkman",
                            Phonenumber = "(005)286-9624 x5816",
                            Photo = "https://randomuser.me/api/portraits/men/46.jpg",
                            Sex = "M",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 47, DateTimeKind.Utc).AddTicks(2980)
                        },
                        new
                        {
                            Id = 666,
                            Address = "7610 Nelda Drives",
                            Birthdate = new DateTime(1999, 5, 23, 2, 42, 51, 975, DateTimeKind.Utc).AddTicks(3280),
                            City = "Zemlakburgh",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 975, DateTimeKind.Utc).AddTicks(7700),
                            Email = "dorian_kreiger@leopold.ca",
                            Favorite = false,
                            Name = "Vidal Spencer",
                            Phonenumber = "1-537-584-103110 x484",
                            Photo = "https://randomuser.me/api/portraits/women/9.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 975, DateTimeKind.Utc).AddTicks(8070)
                        },
                        new
                        {
                            Id = 692,
                            Address = "101536 Nannie Crest",
                            Birthdate = new DateTime(2001, 12, 14, 6, 9, 28, 26, DateTimeKind.Utc).AddTicks(1120),
                            City = "North Kathleen",
                            Country = "Northern Ireland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 26, DateTimeKind.Utc).AddTicks(6780),
                            Email = "friedrich@warren.us",
                            Favorite = false,
                            Name = "Vinnie Schmidt",
                            Phonenumber = "1-914-368-8906 x9138",
                            Photo = "https://randomuser.me/api/portraits/women/35.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 25, 26, DateTimeKind.Utc).AddTicks(7180)
                        },
                        new
                        {
                            Id = 662,
                            Address = "8222 Rutherford Overpass",
                            Birthdate = new DateTime(1983, 10, 24, 15, 14, 17, 968, DateTimeKind.Utc).AddTicks(1430),
                            City = "East Aurelia",
                            Country = "Scotland",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 968, DateTimeKind.Utc).AddTicks(6680),
                            Email = "granville_howe@ressie.co.uk",
                            Favorite = false,
                            Name = "Virgie Walsh",
                            Phonenumber = "(0410)1000-10571 x941010",
                            Photo = "https://randomuser.me/api/portraits/women/5.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 968, DateTimeKind.Utc).AddTicks(7100)
                        },
                        new
                        {
                            Id = 676,
                            Address = "8605 Mertz Crest",
                            Birthdate = new DateTime(1985, 6, 15, 5, 9, 3, 996, DateTimeKind.Utc).AddTicks(6050),
                            City = "Lake Terranceton",
                            Country = "Wales",
                            CreatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 997, DateTimeKind.Utc).AddTicks(960),
                            Email = "rogers_dietrich@monroe.org",
                            Favorite = false,
                            Name = "Zakary Kertzmann",
                            Phonenumber = "1-687-600-1737",
                            Photo = "https://randomuser.me/api/portraits/women/19.jpg",
                            Sex = "F",
                            UpdatedTs = new DateTime(2016, 12, 19, 19, 43, 24, 997, DateTimeKind.Utc).AddTicks(1340)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
